version: "3.8"

services:
#  nginx:
#    image: nginx:alpine
#    container_name: doctor-nginx
#    working_dir: /var/www/html
#    volumes:
#      - ./backend:/var/www/html
#      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
#      - ./docker/data/logs/nginx:/var/log/nginx/
#    ports:
#      - "80:80"
#    depends_on:
#      - php
#    networks:
#      - doctor

  nginx-unit:
    build: ./docker/nginx-unit
    image: unit:1.31.0-php8.2
    container_name: doctor-nginx-unit
    volumes:
      - ./backend:/var/www/html
      - ./docker/nginx-unit/config.json:/docker-entrypoint.d/config.json
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
    working_dir: /var/www/html
    ports:
      - "80:80"
    depends_on:
      - postgres
    networks:
      - doctor

#  php:
#    build: docker/php
#    container_name: doctor-php
#    working_dir: /var/www/html
#    volumes:
#      - ./backend:/var/www/html
#      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
#    depends_on:
#      - postgres
#    networks:
#      - doctor

  postgres:
    image: postgres:latest
    container_name: doctor-postgres
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./docker/data/postgres:/home/db
    environment:
      - POSTGRES_DB=doctor
      - POSTGRES_USER=doctor
      - POSTGRES_PASSWORD=doctor
    ports:
      - "5432:5432"
    networks:
      - doctor

networks:
  doctor:
    name: doctor
    driver: bridge

volumes:
  postgres:
